trigger:
  - main

pool:
  name: 'selfhosted'
  #vmImage: 'ubuntu-latest'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js version 16.x'

  - script: |
      npm install yarn -g
    displayName: 'Install yarn'

  - script: |
      yarn install
    displayName: 'Install Dependencies'

  - task: Cache@2
    displayName: 'Cache build/cache'
    inputs:
      key: next | $(Agent.OS) | yarn.lock
      path: '$(System.DefaultWorkingDirectory)/build/cache'

  - script: |
      yarn run build
    displayName: 'Build NextJS App'

  - task: CopyFiles@2
    displayName: 'Copy File to: $(TargetFolder)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '$(Build.BuildId).zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

  - task: ArchiveFiles@1
    displayName: 'Archive files'
    inputs:
      rootFolder: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      replaceExistingArchive: true
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: RacketWeb'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
