trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npm run test
    displayName: 'npm test'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(29854bc5-5fe7-46e0-a758-1d1950748b0d)'
      appType: 'webAppLinux'
      WebAppName: 'racketWeb'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      StartupCommand: 'npm run start'
