trigger:
  - main

pool:
  name: 'selfhosted'
  #vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run build
    displayName: 'Build NextJS App'  

  - task: CopyFiles@2
    displayName: 'Copy File to: $(TargetFolder)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '$(Build.BuildId).zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'  

  - task: ArchiveFiles@1
    displayName: 'Archive files'
    inputs:
      rootFolder: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false 
      replaceExistingArchive: true 
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
 

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: RacketWeb'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
