trigger:
  - main

pool:
  name: 'selfhosted'
  #vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build NextJS App'

  - task: ArchiveFiles@1
    displayName: 'Archive files '
    inputs:
      rootFolder: '$(System.DefaultWorkingDirectory)/.next/'
      includeRootFolder: false
      archiveType: 'zip'
      verbose: true
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: CopyFiles@2
    displayName: 'Copy File to: $(TargetFolder)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '$(Build.BuildId).zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(29854bc5-5fe7-46e0-a758-1d1950748b0d)'
      appType: 'webAppLinux'
      WebAppName: 'racketWeb'
      packageForLinux: '$(System.WorkFolder)/$(Build.BuildId).zip'
      #packageForLinux: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
      StartupCommand: 'npm run start'

  # - task: AzureWebApp@1
  #   inputs:
  #     azureSubscription: 'Azure subscription 1(29854bc5-5fe7-46e0-a758-1d1950748b0d)'
  #     appType: 'webAppLinux'
  #     appName: 'racketWeb'
  #     runtimeStack: 'NODE|16-lts'
  #     startUpCommand: 'npm start'
  #     deploymentMethod: 'zipDeploy'
  #     package: '$(System.DefaultWorkingDirectory)/1/package/$(Build.BuildId).zip'
  #   displayName: 'Deploy Next.js app to Azure'
